version: '3'
vars:
  BIN_DIR: "{{.ROOT_DIR}}/bin"
tasks:
  go:build-cmd:
    internal: false
    cmds:
      - go build -o "{{.BIN_DIR}}/{{.GO_TARGET}}" ./cmd/{{.GO_TARGET}}
  go:test:
    internal: false
    cmds:
      - go test "./internal/{{.GO_TARGET}}"
  go:run-cmd:
    internal: false
    cmds:
      - go run "./cmd/{{.GO_TARGET}}"
  build:service:
    cmds:
      - task: go:build-cmd
        vars:
          GO_TARGET: sensor-service
  build:service-image:
    cmds:
      - |
        docker buildx build \
          -f cmd/sensor-service/Dockerfile \
          . \
          -t ghcr.io/s0cks/sp-interview-prep-01-sensor-service:latest
  build:mock-sensor-image:
    cmds:
      - |
        docker buildx build \
          -f test/sensor-mock/Dockerfile \
          test/sensor-mock/ \
          -t ghcr.io/s0cks/sp-interview-prep-01-sensor-mock:latest
  build:web-image:
    cmds:
      - |
        docker buildx build \
          -f client/Dockerfile \
          client/ \
          -t ghcr.io/s0cks/sp-interview-prep-01-sensor-web:latest
  test:service:
    cmds:
      - task: go:test
        vars:
          GO_TARGET: sensor
  run:service:
    cmds:
      - task: go:run-cmd
        vars:
          GO_TARGET: sensor-service
  build:
    deps:
      - build:service
      - build:service-image
      - build:mock-sensor-image
      - build:web-image
  test:
    deps:
      - test:service
  default:
    cmds:
      - task: build
