version: '3'
vars:
  BIN_DIR: "{{.ROOT_DIR}}/bin"
tasks:
  go:build-cmd:
    internal: false
    cmds:
      - go build -o "{{.BIN_DIR}}/{{.GO_TARGET}}" ./cmd/{{.GO_TARGET}}
  go:test:
    internal: false
    cmds:
      - go test "./internal/{{.GO_TARGET}}"
  go:run-cmd:
    internal: false
    cmds:
      - go run "./cmd/{{.GO_TARGET}}"
  build:service:
    cmds:
      - task: go:build-cmd
        vars:
          GO_TARGET: sensor-service
  build:images:
    cmds:
      - docker compose build
  test:service:
    cmds:
      - task: go:test
        vars:
          GO_TARGET: sensor
  run:service:
    cmds:
      - task: go:run-cmd
        vars:
          GO_TARGET: sensor-service
  # requires [ouch](https://github.com/ouch-org/ouch)
  ouch:compress:
    internal: true
    vars:
      ROOT_DIR_NAME:
        sh: basename "{{.ROOT_DIR}}"
    cmds:
      - |
        ouch compress \
          .github \
          client/ \
          cmd/ \
          docs/ \
          internal/ \
          test/ \
          CHANGELOG.md \
          docker-compose.yaml \
          .dockerignore \
          .gitignore \
          .release-please-manifest.json \
          .yamllint \
          go.mod \
          go.sum \
          LICENSE \
          openapi.yaml \
          README.md \
          release-please-config.json \
          Taskfile.yaml \
          {{.ROOT_DIR_NAME}}-sources.{{.OUCH_COMPRESSION}}
  zip:
    cmds:
      - task: ouch:compress
        vars:
          OUCH_COMPRESSION: zip
  targz:
    cmds:
      - task: ouch:compress
        vars:
          OUCH_COMPRESSION: tar.gz
  build:
    deps:
      - build:service
      - build:images
  test:
    deps:
      - test:service
  clean:cleanrf:
    internal: true
    cmds:
      - rm -rf {{.CLEAN_TARGETS}}
  clean:bin:
    cmds:
      - task: clean:cleanrf
        vars:
          CLEAN_TARGETS: bin/*
  clean:source-archive:
    vars:
      ROOT_DIR_NAME:
        sh: basename "{{.ROOT_DIR}}"
    cmds:
      - task: clean:cleanrf
        vars:
          CLEAN_TARGETS: "{{.ROOT_DIR_NAME}}-sources.*"
  clean:
    deps:
      - clean:bin
      - clean:source-archive
  default:
    cmds:
      - task: build
